### ISSUE TITLE
Python 3 imports in __init__.py

### ISSUE THREAD

**Issue by sujitnair** [agiliq/merchant#119]
I get

ImportError: No module named 'gateway'

When I import billing in Python 3.3. The solution is to replace biling/__init__.py with 

from .gateway import Gateway, get_gateway, GatewayNotConfigured
from .integration import Integration, get_integration, IntegrationNotConfigured
from .utils.credit_card import CreditCard

Everything seems ok. To get Amazon/Paypal to work I also needed to replace __init__.py inside billing/models to have the right import syntax in Python 3.3

**Comment by theju** [comment]
Python3 migration was not completely done as mentioned in #112. I pushed in some changes and some gateways and integrations still won't work. Can you please confirm that Amazon FPS and PayPal work for you?

**Comment by sujitnair** [comment]
Yes, Amazon FPS, Stripe and PayPal works for me. I haven't tried anything else.

**Comment by theju** [comment]
Thanks for verifying. Yes, some of the other gateways and integrations have issues as in the upstream library is still not supported on Python3.
